name: Mi primer workflow

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Ver archivos del repo
        run: ls -la

      - name: Ejecutar un script
        run: |
          echo "Estoy dentro del runner"
          pwd
